In [7]:
import os
from dotenv import load_dotenv
import pandas as pd

In [8]:
load_dotenv()

True

In [9]:
pd.options.display.max_columns=False
df = pd.read_csv(os.getenv('cleaned_csv_path'))

In [10]:
df

       duration_ms  danceability  energy  loudness  ...  instrumentalness  liveness  valence    tempo
0           161427         0.563  0.1840   -13.757  ...          0.000016    0.3250    0.654  133.088
1           223440         0.427  0.1800   -15.375  ...          0.000000    0.1280    0.431   78.459
2           208267         0.511  0.2060   -15.514  ...          0.000000    0.4180    0.481   70.443
3           161933         0.676  0.4670   -12.393  ...          0.000000    0.2190    0.726  129.775
4           167973         0.650  0.2980   -13.806  ...          0.000000    0.3730    0.844   75.950
...            ...           ...     ...       ...  ...               ...       ...      ...      ...
95832       174800         0.674  0.5680    -6.356  ...          0.000000    0.1650    0.640  166.107
95833       265846         0.528  0.6730    -3.639  ...          0.000000    0.0989    0.297  130.066
95834        82500         0.609  0.0172   -28.573  ...          0.973000    0.1080    0.890   68.619
95835       185250         0.562  0.0331   -25.551  ...          0.961000    0.1110    0.386   63.696
95836       258267         0.560  0.5180    -7.471  ...          0.000000    0.0648    0.211  131.896

[95837 rows x 10 columns]

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df)

X_scaled.shape

(95837, 10)

In [16]:
X_scaled = pd.DataFrame(X_scaled, columns=df.columns)
X_scaled

       duration_ms  danceability    energy  loudness  ...  instrumentalness  liveness   valence     tempo
0        -0.401735     -0.153476 -1.511128 -0.757909  ...         -0.353338  0.538584  0.321287  0.515005
1         0.124906     -1.028518 -1.528056 -1.098629  ...         -0.353405 -0.521537 -0.577455 -1.294487
2        -0.003949     -0.488051 -1.418027 -1.127899  ...         -0.353405  1.039046 -0.375943 -1.560003
3        -0.397437      0.573581 -0.313510 -0.470677  ...         -0.353405 -0.031836  0.611464  0.405268
4        -0.346143      0.406294 -1.028695 -0.768227  ...         -0.353405  0.796887  1.087031 -1.377593
...            ...           ...       ...       ...  ...               ...       ...       ...       ...
95832    -0.288165      0.560713  0.113908  0.800599  ...         -0.353405 -0.322428  0.264864  1.608703
95833     0.485036     -0.378671  0.558254  1.372746  ...         -0.353405 -0.678133 -1.117507  0.414907
95834    -1.072017      0.142494 -2.217003 -3.877872  ...          3.832648 -0.629163  1.272422 -1.620420
95835    -0.199419     -0.159910 -2.149717 -3.241498  ...          3.781021 -0.613019 -0.758816 -1.783486
95836     0.420672     -0.172778 -0.097685  0.565801  ...         -0.353405 -0.861636 -1.464107  0.475522

[95837 rows x 10 columns]

In [17]:
X_scaled.describe().round(2)

       duration_ms  danceability    energy  loudness  ...  instrumentalness  liveness   valence     tempo
count     95837.00      95837.00  95837.00  95837.00  ...          95837.00  95837.00  95837.00  95837.00
mean         -0.00          0.00      0.00      0.00  ...              0.00     -0.00      0.00     -0.00
std           1.00          1.00      1.00      1.00  ...              1.00      1.00      1.00      1.00
min          -1.72         -3.78     -2.29     -8.43  ...             -0.35     -1.21     -2.31     -3.89
25%          -0.44         -0.64     -0.75     -0.54  ...             -0.35     -0.67     -0.79     -0.75
50%          -0.04          0.12      0.00      0.16  ...             -0.35     -0.41      0.06     -0.03
75%           0.35          0.73      0.79      0.73  ...             -0.35      0.41      0.83      0.61
max          38.99          2.60      1.94      3.27  ...              3.95      4.15      1.72      4.05

[8 rows x 10 columns]